### ISSUE TITLE
某些情况无法侧滑返回

### ISSUE THREAD

**Issue by lbw718733550** [ParfoisMeng/SlideBack#1]
在界面有 recycleView 和 scrollView , 地图， 等情况下无法显示侧滑ui 和侧滑返回，应该是被拦截了

**Comment by ParfoisMeng** [comment]
可能吧。
我晚上下班后看看，排查一下。
感谢反馈。

**Comment by ParfoisMeng** [comment]
@lbw718733550 
最近项目略忙。今晚抽空看了下，是滑动冲突的问题。事件被消费没到decorView的OnTouch。
试了一下，自定义相关可滑动控件可以解决此问题，但这并不是一个良好的解决方案。NestedScrolling也许是个办法，我准备过两天有空研究一下。现在就先休息了。

如果您有什么解决方案，十分欢迎PR。

**Comment by ParfoisMeng** [comment]
请更新1.0.3

解决方案简述：
注册方法加了个haveScroll，如果为true则将原根布局抽出来，套上一层处理滑动冲突的Layout再塞回去。
处理滑动冲突的Layout：[SlideBackInterceptLayout](https://github.com/ParfoisMeng/SlideBack/blob/master/slidebacklib/src/main/java/com/parfoismeng/slidebacklib/widget/SlideBackInterceptLayout.java)

PS：感觉此方式不是十分理想（市面上好像都是这么解决的），但目前没有更好的思路。如果您有什么想法，请与我沟通，十分欢迎PR。
