### ISSUE TITLE
可以仿微信的侧滑返回吗

### ISSUE THREAD

**Issue by czl0325** [ParfoisMeng/SlideBack#13]

**Comment by ParfoisMeng** [comment]
[README的前情中有对此进行说明](https://github.com/ParfoisMeng/SlideBack/blob/master/README.md#%E5%89%8D%E6%83%85)

![image](https://user-images.githubusercontent.com/14328312/83018547-151cda00-a058-11ea-98fb-4ac1f538c696.png)

**Comment by czl0325** [comment]
能写到demo里吗？一直没找到好的实现

**Comment by ParfoisMeng** [comment]
= =
意思是本库没有使用仿微信的效果。
方案1、2都可以实现仿微信侧滑返回的效果，但是方案3是类全面屏返回效果，与仿微信返回效果不一样的。
私以为，方案1基本是不可取了。方案2需要上页ContentView截图并绘制到当前页，操作Bitmap难免消耗性能。

一定要仿微信效果的话，你可以试试[ ParallaxBackLayout ](https://github.com/anzewei/ParallaxBackLayout)。但是该库还是没有使用Kotlin、依然使用support包，并且大半年没更新了。。。

**Comment by czl0325** [comment]
上页ContentView截图并绘制到当前页  
微信应该不是这么做的吧，这该多影响性能啊！
