### ISSUE TITLE
多次切换页面时alpha会出错

### ISSUE THREAD

**Issue by czhah** [ParfoisMeng/SlideBack#16]
问题：两个activity都注册了侧滑返回，都是自定义标题栏，且给标题栏设置蓝色背景，A页面跳转B页面时再退回A页面，重复几十次会出现B页面标题栏变成透明的(实际测试重复几次就出现了)，手动触发一下侧滑功能，立即恢复蓝色背景；
原因：SlideBackIconView的初始拉动距离为0，绘制时alpha = slideLength / maxSlideLength - 0.2f，透明度为负值；
解决：透明度设置不为负数就不会出现了；

**Comment by ParfoisMeng** [comment]
未能复现，但相关代码已修改。请更新v1.1.2。
```
alpha = max(currentSlideLength / viewMaxLength - 0.2f, 0f)
```
