### ISSUE TITLE
Fragment支持？

### ISSUE THREAD

**Issue by SilenceJR** [ParfoisMeng/SlideBack#2]
支持Fragment么？

**Comment by ParfoisMeng** [comment]
您可以在Fragment的父级Activity中注册SlideBack，然后在SlideBackCallBack中remove栈顶的Fragment。

**Comment by ParfoisMeng** [comment]
如果我的回复能解决您的疑问，请您关闭此issues。如果还有疑问请继续回复。
如未关闭且无后续回复，3天后将由我关闭。
