### ISSUE TITLE
demo体验

### ISSUE THREAD

**Issue by diorslau** [ParfoisMeng/SlideBack#3]
感觉阻尼太大了吧, 用用力滑到右边才返回...    跟ios那种侧滑返回还是有点差距    感觉一般用户在浏览页面的时候都是轻轻一划的

**Comment by ParfoisMeng** [comment]
默认SlideBackIconView的控件宽度是1/12屏幕宽，ACTION_MOVE时只响应移动距离的1/4(阻尼?)，拖动1/3屏幕宽的长度时，就会触发事件。
之前在设计时考虑了自定义这个响应距离与比例(阻尼?)，但是又觉得这个大概是通用的，也因为懒，封装时就没有开放出来。
既然有需求，那这两天我看看怎么组织一下把设置方法提供出来。

**Comment by ParfoisMeng** [comment]
@diorslau 
已更新1.0.4，如有需要请更新。
调整了默认的阻尼系数，且提供自定义方法。
