### ISSUE TITLE
1.0.3问题的属性

### ISSUE THREAD

**Issue by kdsrsl** [ParfoisMeng/SlideBack#5]
请问 haveScroll属性，是Builder配置上去的。
意思是 必须要知道 这个页面是否有可滑动布局？

**Comment by ParfoisMeng** [comment]
对。
haveScroll默认为false，也就是默认认为页面内不包含可滑动布局。
这么做的原因是，haveScroll=true时，即页面有滑动布局时，SlideBack在初始化加载时会：
1. 将原根布局取出
2. 换上一个处理滑动冲突的布局为根布局
3. 将原根布局add回去

我没有实际测试过这种处理的性能损耗，但我觉得能省一点是一点吧。毕竟并不是所有页面都可滑动嘛。
* 当然，如果页面没有可滑动布局，设置成true，对应用也没有影响。

**Comment by kdsrsl** [comment]
目前市面上的 app ，很少有不可滑的界面吧。。。。
一般为了方便，这种功能都会放到基类里，这时候再去手动指定haveScroll就繁琐了。

不过还是谢谢，代码注释真详细。
