### ISSUE TITLE
右侧的侧滑无法生效

### ISSUE THREAD

**Issue by wizos** [ParfoisMeng/SlideBack#6]
现象：开启 edgeMode(SlideBack.EDGE_BOTH) 后，右侧侧滑还是无法生效。

原因：SlideBackInterceptLayout 内。
`@Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return ev.getAction() == MotionEvent.ACTION_DOWN && ev.getRawX() <= sideSlideLength;
    }`

没有对右侧的手势做拦截。

**Comment by ParfoisMeng** [comment]
@wizos 
非常感谢帮忙提出Bug。
现已修复，更新1.0.6即可。
