### ISSUE TITLE
该升级升级了

### ISSUE THREAD

**Issue by wardenlzr** [ParfoisMeng/SlideBack#7]
Android dependency 'com.android.support:appcompat-v7' has different version for the compile (26.1.0) and runtime (28.0.0) classpath. You should manually set the same version via DependencyResolution

如果剔除掉
//侧滑返回
    api 'com.github.ParfoisMeng:SlideBack:1.0.6'{
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
就会如下错
Could not find method com.github.ParfoisMeng:SlideBack:1.0.6() for arguments [build_ozn05o2r6l8vp66zanhc2qoc$_run_closure3$_closure10@163af1d9] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by ParfoisMeng** [comment]
看起来，该升级的是你的项目。
此库使用的v7版本为28.0.0，具体用处为内部几处约束(@Nullable/@ColorInt/@IntDef)。
解决方案：
1. 下载源码，去除v7依赖或更改版本号。
2. 更新你的项目中的v7库为28.0.0，并更新相关第三方库版本(个人觉得更像是你的项目依赖的某第三方库使用了26.1.0)。
